---
title: "Basics of R"
author: "Michael Chow"
date: "February 10, 2016"
output:
  html_document:
    toc: yes
    toc_depth: 2
---

Arithmetic
----------

```{r}
1 + 1

2 * 2

5 / 2

2^4

7 %% 2
```

Character Strings
-----------------

```{r}
"I am a string of characters"

'I am also a string of characters'

" I'm a character with ' in it "
```


Variables
---------

```{r}
x <- 1
1 + x

y <- 1 + x

no_spaces_allowed_in_varnames <- "a character string"
```

Functions
---------

```{r}
log(1)

min(3, 1)

max(3, 1)

paste("I am a", "string of words")

# Can use variables with functions
x <- 1
log(x)

# Some functions have optional arguments
log(100)
e <- exp(1)
log(100, base = e)
log(100, base = 10)
```

### In general, adding spaces doesn't matter!

```{r}
# right way
min(3, 1)

# wrong but works
min(3,         1)
min        (3,1)
min(      3,1)
```


Vectors
------

### Basic vector creation

```{r}
# c is a function to create vectors
c(1,2,3,4)

# we can also use the colon operator
1:4 

# from:to
-2:2

# can go in reverse
2:-2
```

### Some useful functions for creating vectors

```{r}
# seq(from, to, by)
# the line below starts at 1, and goes to 4, counting up by 2
# note that it will not go above 4
seq(1,4, 2)

# rep(vector, times)
rep(1, 4)
```

### Describing vectors

```{r}
numbers <- 1:10
words <- c("one", "two", "three")

length(numbers)

class(numbers)
class(words)
```

### A single number is a vector!

```{r}
1

length(1)
```


Vector arithmetic
-----------------

### Basic, everything is the same length

```{r}
ones <- rep(1, 4)
to_four <- 1:4

length(ones)
length(to_four)

ones + to_four
```

### Recycling

```{r}
x <- 1:2
ones <- rep(1, 4)

ones
x

ones + x

y <- 1:3
ones + y
```

Basic Indexing
--------------
```{r}
ones <- rep(1,4)

# use a vector of the positions you're interested in
ones[c(1,2)]
ones[1:2]
```

Alternatively, you can give the elements of your vector each a name.
Once an element has a name, you can use it to select that element.

```{r}
avec <- c(a=1, b=2)
names(avec)
avec

# get the element named 'a'
avec['a']

# be careful about giving elements the same name
newvec <- c(a=1, b=2, a=3)
newvec['a']   # only gets first element named 'a'!
```

Glossary
========

```{r, eval=FALSE}
log
exp
min
max
paste
seq
rep
c
length
class
an_array[c(1,2)]
an_array$varname
```